modules:
  protofiles:
    type: ProtoFiles
    network: ./assets/equil/equil-network.binpb
    population: ./assets/equil/equil-plans.binpb
    vehicles: ./assets/equil/equil-vehicles.binpb
    ids: ./assets/equil/ids.binpb
  partitioning:
    type: Partitioning
    num_parts: 12
    method: !Metis
  output:
    type: Output
    output_dir: ./assets/equil/output
    write_events: Proto
  routing:
    type: Routing
    mode: UsePlans
  simulation:
    type: Simulation
    start_time: 0
    end_time: 86400
    sample_size: 1.0
    stuck_threshold: 1000

