name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install other libraries
        run: sudo apt -y install libclang-dev llvm-dev libmetis-dev libopenmpi-dev
      - name: Build
        run: cargo build --release
      - name: Install mpirun
        run: cargo install --force cargo-mpirun
      - name: Run tests
        env:
          RUST_BACKTRACE: 1
        run: cargo test --release --verbose -- --test-threads=1
